project:
  type: website

website:
  title: "Job Market Analysis 2024"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: introduction.qmd
        text: "Project Overview"
      - href: data_cleaning.qmd
        text: "Data Preparation"
      - href: salary_compensation_trends.qmd
        text: "Salary & Compensation trends"


format:
  html:
    theme: cosmo
    toc: true
execute:
  echo: true
  eval: true
  code-fold: true